# Generated by Django 4.0.1 on 2022-07-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('tag1', models.CharField(max_length=255)),
                ('tag2', models.CharField(max_length=255)),
                ('tag3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='funchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=255)),
                ('question2', models.CharField(max_length=255)),
                ('question3', models.CharField(max_length=255)),
                ('question4', models.CharField(max_length=255)),
                ('question5', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
